# Generated by Django 4.1.4 on 2023-04-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "picture",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=300)),
                ("completed", models.BooleanField(default=False)),
                (
                    "item_list",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="List.todolist",
                    ),
                ),
            ],
        ),
    ]
