# Generated by Django 4.1.4 on 2023-04-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listitem",
            name="item_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list_items",
                to="List.todolist",
            ),
        ),
    ]
