# Generated by Django 4.1.4 on 2023-04-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0002_alter_listitem_item_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="picture",
            field=models.ImageField(upload_to="images"),
        ),
    ]
