# Generated by Django 4.1.4 on 2023-04-30 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("List", "0004_todolist_likes_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="likes",
        ),
        migrations.AddField(
            model_name="todolist",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
