# Generated by Django 4.1.4 on 2023-04-30 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0005_remove_todolist_likes_todolist_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
