# Generated by Django 4.1.4 on 2023-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0008_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completed",
            name="media_file",
            field=models.FileField(upload_to="completed_media/"),
        ),
    ]
