# Generated by Django 4.1.4 on 2023-05-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("List", "0009_alter_completed_media_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="completed",
            name="completer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completer",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
