# Generated by Django 4.1.4 on 2023-05-02 23:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0011_profile_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
