# Generated by Django 4.1.4 on 2023-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0013_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(max_length=900),
        ),
    ]
