# Generated by Django 4.1.4 on 2023-05-03 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("List", "0014_profile_facebook_url_profile_instagram_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="favourites",
            field=models.ManyToManyField(
                blank=None,
                default=None,
                related_name="favourite",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
