# Generated by Django 4.1.4 on 2023-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0016_remove_profile_about_profile_bio_profile_occupation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
