# Generated by Django 4.1.4 on 2023-05-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0018_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
