# Generated by Django 4.2.3 on 2023-07-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("List", "0019_alter_todolist_completion_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todolist",
            options={"ordering": ("-created",), "verbose_name_plural": "Todo Lists"},
        ),
        migrations.AddField(
            model_name="todolist",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
